version: "3"
services:
  db:
    container_name: db
    image: mysql:8.0.32
    ports:
      - "3307:3306"
    expose:
      - 3307
    environment:
      MYSQL_USER: alpha
      MYSQL_ROOT_PASSWORD: abcxyz
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
    restart: always
  app:
    container_name: sparkxyz
    depends_on:
      - db
    links:
      - db
    build: ./
    ports:
      - "8001:8000"
    expose:
      - 8001
    environment:
      MYSQL_USER: alpha
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_HOST: db
    restart: always